# Generated by Django 4.1.3 on 2022-11-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('like_count', models.IntegerField(blank=True, default=0)),
                ('unlike_count', models.IntegerField(blank=True, default=0)),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
                ('unlike', models.ManyToManyField(blank=True, related_name='unlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
